name: 'set-make-job-count'
description: 'Set the MAKE_JOB_COUNT environment variable to a value suitable for the host runner'
runs:
  using: "composite"
  steps:
    - name: set-jobs-macOS
      run: |
        echo MAKE_JOB_COUNT=$(printf '%s\n%s' $(( $(sysctl -n hw.memsize) * 4 / (1073741824 * 11) )) $(sysctl -n hw.logicalcpu) | sort -n | head -n1 | sed -e 's/^0$/1/') >> $GITHUB_ENV
      shell: bash
      if: runner.os == 'macOS'
    - name: set-jobs-windows
      run: |
        echo MAKE_JOB_COUNT=$(printf '%s\n%s' $(( $(grep MemTotal: /proc/meminfo | cut -d: -f2 | cut -dk -f1) * 4 / (1048576 * 11) )) $(nproc) | sort -n | head -n1 | sed -e 's/^0$/1/') >> $GITHUB_ENV
      shell: msys2 {0}
      if: runner.os == 'Windows'
    - name: set-jobs-linux
      run: |
        echo MAKE_JOB_COUNT=$(printf '%s\n%s' $(( $(vmstat -s --unit M | grep 'total memory' | cut -dM -f1) * 4 / (1024 * 11) )) $(nproc) | sort -n | head -n1 | sed -e 's/^0$/1/') >> $GITHUB_ENV
      if: runner.os == 'Linux'
      shell: bash
